### PR TITLE
Disable ui component by default, enable it at BlockCanary.install()

### PR DESCRIPTION
**Pull request by Piasy**
1. move blockcanary-ui into blockcanary-android;
2. then we could disable ui component by default, enable it at BlockCanary.install();
3. this feature let us compile blockcanary-android into release build but not showing BlockActivity, because in some case, we could not use debugCompile and releaseCompile at the same time;
4. rename blockcanary-no-op to blockcanary-android-no-op, like LeakCanary;
5. not depends on modules via maven, it won't affect maven publish;

### CODE REVIEW

**Comment by markzhai** [comment]
The reason I separate `blockcanary-android` and `blockcanary-ui` is to not compile UI related codes if we don't need it like in release package.

Not quite sure what do you mean by `we could not use debugCompile and releaseCompile at the same time`, the way to use blockcanary is various, and developer can assemble by themselves.

**Comment by Piasy** [comment]
For clean release build, `no-op` is enough, right?

I use facebook BUCK build, and generate BUCK file automatically, my [BUCK generator](https://github.com/Piasy/OkBuck) could not utilize the `debugCompile` and `releaseCompile` option, so I plan to ship `blockcanary-android` into release build, but not showing the BlockActivity entrance.

If you don't want to accept this pr, I think there are two options for me: improve my BUCK generator, or create my customized block canary build.

**Comment by markzhai** [comment]
@Piasy 

        // if set true, notification will be shown, else only write log file
        @Override
        public boolean isNeedDisplay() {
            return BuildConfig.DEBUG;
        }

Have you tried to use this context configuration, this can prevent showing the BlockActivity entrance?

**Comment by Piasy** [comment]
`isNeedDisplay` only control whether show notification, right? If we do not disable the `DisplayBlockActivity` component in manifest or code by default, the `block` icon will showed in launcher, because it's another `entrance activity`.

**Comment by markzhai** [comment]
@Piasy I see, maybe I removed the setComponentEnabledSetting sometime... This PR is accepted as I found separate this library into too many modules makes it hard to understand for developers.

**Comment by Piasy** [comment]
Thanks! Hope to see a new version in maven. :)

**Pull request merged**
